version: '3.8'
services:
  api:
    container_name: marksheet_api_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
      - ./drizzle:/usr/src/app/drizzle
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./drizzle.config.ts:/usr/src/app/drizzle.config.ts
      - ./.env:/usr/src/app/.env
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - marksheet_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    container_name: marksheet_redis_dev
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - marksheet_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  postgres:
    container_name: marksheet_postgres_dev
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - marksheet_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  pgdata:
    name: marksheet_pgdata_dev
networks:
  marksheet_net:
    name: marksheet_network_dev
