FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Install dependencies only if needed
COPY package*.json ./

RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Enable hot-reload
CMD ["npm", "run", "start:dev"]
